# Generated by Django 6.0.3 on 2026-03-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#f3f4f6', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('font_family', models.CharField(choices=[('font-sans', 'Sans'), ('font-serif', 'Serif'), ('font-mono', 'Mono')], default='font-sans', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='biodata',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
    ]
